version: "3.8"
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python", "main.py"]

  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    command: ["python", "bot.py"]
