name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render health endpoint
        run: |
          echo "Pinging Render healthcheck..."
          curl -s -o /dev/null -w "%{http_code}" https://finance-tracker-1ifk.onrender.com/health
